In [2]:
import pandas as pd

# DataFrames
- Diferentemente de um série, um data frame é uma estrutura de duas dimensões
    - Possui linhas e colunas
- É como se fosse uma tabela do excel ou google sheets
- Como possui multiplas linhas e colunas, precisamos de dois pontos de referência para recuperar um valor (na série era apenas um)
    - Por isso tem duas dimensoes
    - O numero de linhas e colunas nao importam
- É o foco principal dessa biblioteca

## Explorando dados da NBA
- Para começar, vamos carregar um dataframe (DF) usando o já conhecido `read_csv()`

In [3]:
nba = pd.read_csv("../data/nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Como já mencionado, o DF tem a cara de uma tabela
    - Nesse caso, possui 9 colunas e 458 linhas
- Assim como na série, possui os indices, que foram gerados automaticamente e são numericos (mas poderiam ser labels)
- Podemos imaginar cada coluna como se fosse uma série
- Observe que temos varios `NaN` na tabela, inclusive uma linha inteira (a ultima)
    - Nota: por ter NaN a lib força uma coluna de inteiros se tornar um float, como a da idade

## Métodos e atributos
- Muitos métodos da série funciona para um DF
- Vamos começar por esses métodos em comum. Como já foi abordado anteriormente, nao vamos investir muito tempo neles (a nao ser que seja necessario)

In [6]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [7]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [13]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

- Observe que values retorna a numpy array, ou seja, por baixo dos panos, a lib envelopa numpy arrays
- Podemos checar o shape

In [14]:
nba.values.shape

(458, 9)

- ou, simplesmente:

In [15]:
nba.shape

(458, 9)

In [16]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

- Agora vamos ver métodos exclusivos do DF

In [19]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

- Perceba que as colunas vem como Index. Podemos imaginar que o DF tem os index das linhas e das colunas
- E podemos obter ambos os index:

In [20]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

- Obtendo informações com `info()` e `describe()`

In [21]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [22]:
nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

## Métodos com comportamento diferente
- Alguns métodos existem para séries e dataframes, porém possuem comportamentos diferentes em termos de parametros e resultados
- Por exemplo, o método `sum()`, `mean()`, `max()` e `min()`
- Para demostrar isso vamos carregar um outro dataframe

In [23]:
rev_df = pd.read_csv("../data/revenue.csv", index_col="Date")
rev_df.head()

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933
1/4/16       730          904    885
1/5/16       114           71    253

- Podemos aplicar o método de soma assim como na série, porém, por padrão, vai somar todas as colunas
- E vai nos retornar uma série

In [24]:
rev_df.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

- Podemos passar um parâmetro para somar por índice. Esse parametro nao existe para serie

In [29]:
rev_df.sum(axis=1)

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

- Esse mesmo comportamento vai ocorrer para os outros métodos previamente citados

In [30]:
rev_df.mean(axis=1)

Date
1/1/16     535.333333
1/2/16     686.666667
1/3/16     322.333333
1/4/16     839.666667
1/5/16     146.000000
1/6/16     645.000000
1/7/16     411.333333
1/8/16     771.000000
1/9/16     874.333333
1/10/16    185.000000
dtype: float64

In [31]:
rev_df.max(axis=1)

Date
1/1/16     985
1/2/16     788
1/3/16     933
1/4/16     904
1/5/16     253
1/6/16     936
1/7/16     996
1/8/16     935
1/9/16     954
1/10/16    285
dtype: int64

In [32]:
rev_df.min(axis=0)

New York        14
Los Angeles     20
Miami          115
dtype: int64