In [1]:
import pandas as pd

# Ordenando DataFrames
- Assim como nas séries, podemos usar o método `sort_values()`
- Porém, precisamos informar a coluna para ordenação

In [2]:
nba = pd.read_csv("../data/nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [3]:
nba.sort_values(by="Name")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
nba.sort_values(by="Name", ascending=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
...,...,...,...,...,...,...,...,...,...
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
nba.sort_values(by="Salary", ascending=False, inplace=True)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
...,...,...,...,...,...,...,...,...,...
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Por padrão, os valores com `NaN` são colocados no final
- Veja o Salary aqui:

In [6]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Porem, podemos alterar esse comportamento usando o parametro `na_position`:

In [7]:
nba.sort_values(by="Salary", ascending=False, inplace=True, na_position="first")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN

## Ordenando usando multiplas colunas
- É igualmente fácil, apenas precisamos passar uma lista para o parametro `by` indicando a ordem das colunas a serem consideradas

In [8]:
nba.sort_values(by=["Name", "Salary", "Team"], ascending=[False, True, False], inplace=True)
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Ordenando pelo index
- Assim como para séries, podemos ordenar pelos indices
- Podemos usar o método `sort_index()`

In [9]:
nba.sort_index(ascending=True, inplace=True)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Criando um ranking
- Podemos criar um rank usando o método `rank()`
- Vamos supor que eu queria o ranking de cada jogador de acordo com o salário

In [10]:
nba["Salary"].fillna(0, inplace=True)
nba["Salary"].rank(ascending=False).astype(int)

0       97
1      110
2      452
3      322
4      147
      ...
453    241
454    383
455    214
456    367
457    452
Name: Salary, Length: 458, dtype: int64

- Agora vamos criar uma nova coluna pra essa informação

In [11]:
nba["Rank Salary"] = nba["Salary"].rank(ascending=False).astype(int)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,97
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,110
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0,452
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,322
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,147

# Obtendo os `n` maiores e menores valores
- Vamos supor que queremos obter os `n` maiores e menores valores de uma coluna
- Podemos resolver isso usando o método `sort_values()`
- Porém, é mais interessante (e muitas vezes mais rápido) usar os métodos `nsmallest()` e `nlargest`
- A ideia é similar ao `sort`, porém, ele retorna apenas os `n` desejados

- Vamos obter os 7 jogadores mais pesados da liga:

In [12]:
nba.nlargest(n=7, columns="Weight")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,NaN,12100000.0,54
302,Boban Marjanovic,San Antonio Spurs,40.0,C,27.0,7-3,290.0,NaN,1200000.0,314
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0,43
395,Jusuf Nurkic,Denver Nuggets,23.0,C,21.0,7-0,280.0,NaN,1842000.0,270
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0,199
41,Kevin Seraphin,New York Knicks,1.0,C,26.0,6-10,278.0,NaN,2814000.0,226
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0,11

- Assim como no sort, podemos colocar uma segunda coluna para desempate:

In [13]:
nba.nlargest(n=7, columns=["Weight", "Age"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,NaN,12100000.0,54
302,Boban Marjanovic,San Antonio Spurs,40.0,C,27.0,7-3,290.0,NaN,1200000.0,314
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0,43
395,Jusuf Nurkic,Denver Nuggets,23.0,C,21.0,7-0,280.0,NaN,1842000.0,270
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0,199
41,Kevin Seraphin,New York Knicks,1.0,C,26.0,6-10,278.0,NaN,2814000.0,226
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0,137

- Agora vamos obter os 7 jogadores mais novos da liga usando o `Weight` como desempate

In [14]:
nba.nsmallest(n=7, columns=["Age", "Weight"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0,275
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0,257
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0,181
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120.0,142
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0,305
393,Emmanuel Mudiay,Denver Nuggets,0.0,PG,20.0,6-5,200.0,NaN,3102240.0,205
62,Bruno Caboclo,Toronto Raptors,20.0,SF,20.0,6-9,205.0,NaN,1524000.0,286

- Uma ultima observação: esses métodos funcionam para um série também:

In [15]:
nba["Age"].nlargest(n=6)

298    40.0
304    40.0
400    40.0
102    39.0
261    39.0
101    38.0
Name: Age, dtype: float64

# Usando o método `sample` para pegar amostras aleatórias
- O método `sample` retorna uma quantidade de dados de maneira aleatório
    - Podemos usar o parâmetro `n` para um valor exato ou `frac` para uma %

In [18]:
nba.sample(n=2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
246,Clint Capela,Houston Rockets,15.0,PF,22.0,6-10,240.0,NaN,1242720.0,310
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0,109

In [19]:
nba.sample(n=2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0,444
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0,4

- Observe que cada execução resulta em um valor diferente
- também podemos usar frac, que representa a % de 0 a 1.0

In [20]:
nba.sample(frac=0.01) # 1%

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000.0,111
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0.0,452
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0,108
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,NaN,525093.0,415
344,Joe Johnson,Miami Heat,2.0,SF,34.0,6-7,240.0,Arkansas,261894.0,426

- Outra opção é setar o `axis` que indica se queremos amostrar linhas ou colunas
    - `axis = 0` -> Linhas
    - `axis = 1` -> Colunas
    - O padrão é 0
- Vamos usar `axis=1` com `n=3` para obter 3 colunas aleatórias:

In [22]:
nba.sample(n=3, axis=1).head()

             College     Salary  Rank Salary
0              Texas  7730337.0           97
1          Marquette  6796117.0          110
2  Boston University        0.0          452
3      Georgia State  1148640.0          322
4                NaN  5000000.0          147

- **Pro tip**: se quisermos embaralhar os dados, podemos usar esse método da seguinte forma:

In [30]:
nba_rand = nba.sample(frac=1.0, random_state=8)
nba_rand.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Rank Salary
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0,367
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0,40
306,Tony Parker,San Antonio Spurs,9.0,PG,34.0,6-2,185.0,NaN,13437500.0,45
131,Ronnie Price,Phoenix Suns,14.0,PG,32.0,6-2,190.0,Utah Valley,947276.0,367
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,0.0,452

- O parametro `random_state` é apenas uma semente para reprodução