In [4]:
import pandas as pd

# Usando o método `apply()`
- Já vimos sobre o método `apply()` para colunas e séries
- Mas ele pode ser usado tanto para colunas quanto para linhas

In [5]:
bond = pd.read_csv("../data/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

- Usando o método para colunas

In [8]:
def convert_to_uppercase(name):
    return name.upper()

bond["Actor"] = bond["Actor"].apply(convert_to_uppercase)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,ROGER MOORE,John Glen,275.2,54.5,9.1
Casino Royale,2006,DANIEL CRAIG,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,DAVID NIVEN,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,SEAN CONNERY,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,PIERCE BROSNAN,Lee Tamahori,465.4,154.2,17.9

- Usando para linhas:
    - Neste caso, vamos receber um array como entrada na qual vai ser a sequencia de valores das colunas

In [12]:
def rank_movie(row):
    director = row[2]
    budget = row[4]        
    if director == "Guy Hamilton":
        return "Good"
    elif budget > 80.0:
        return "Good"
    else:
        return "Bad"

bond.apply(rank_movie, axis=1).head()

Film
A View to a Kill         Bad
Casino Royale           Good
Casino Royale           Good
Diamonds Are Forever    Good
Die Another Day         Good
dtype: object

# Usando o método `copy()`
- Esse método cria uma copia de uma coluna ou DF inteiro
- A vantangem é que é outro espaço de memoria e nao vai ser alterado

In [13]:
actor = bond["Actor"].copy()
actor.head()

Film
A View to a Kill           ROGER MOORE
Casino Royale             DANIEL CRAIG
Casino Royale              DAVID NIVEN
Diamonds Are Forever      SEAN CONNERY
Die Another Day         PIERCE BROSNAN
Name: Actor, dtype: object

In [14]:
bond_copy = bond.copy()
bond_copy.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,ROGER MOORE,John Glen,275.2,54.5,9.1
Casino Royale,2006,DANIEL CRAIG,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,DAVID NIVEN,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,SEAN CONNERY,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,PIERCE BROSNAN,Lee Tamahori,465.4,154.2,17.9